/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Voting {
      
    export type CandidateStruct = {name: string, voteCount: BigNumberish}

    export type CandidateStructOutput = [name: string, voteCount: bigint] & {name: string, voteCount: bigint }
  
    }

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "getAllCandidates" | "s_candidates" | "s_hasVoted" | "vote"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getAllCandidates', values?: undefined): string;
encodeFunctionData(functionFragment: 's_candidates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 's_hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getAllCandidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 's_candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 's_hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getAllCandidates: TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >
    

    
    s_candidates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >
    

    
    s_hasVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [_candidateIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getAllCandidates'): TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 's_candidates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 's_hasVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_candidateIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }